name: CI Mobile Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Run Linter Validations
        run: bun run lint
      
      - name: Run Typecheck Validations
        run: bun run typecheck

      - name: Expo Doctor
        run: bunx expo-doctor

      - name: Expo prebuild Validations
        run: bunx expo prebuild --no-install --non-interactive